variables:
  VITE_BASEURL: http://localhost:3000/api/

stages:
  - test
  - build
  - deploy
  - review
  - dast
  - staging
  - canary
  - production
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - performance
  - cleanup

test:
  stage: test
  image: node:lts
  script:
    - npm ci
    - npm run lint
    - npm run test

sast:
  stage: test

build:
  rules:
    - when: never

code_quality:
  rules:
    - when: never

container_scanning:
  rules:
    - when: never

include:
  - template: Auto-DevOps.gitlab-ci.yml
